name: Desploy Infra
on: [push]

jobs:
    infra:
        uses: gh-actions-workflows/terraform-workflows/.github/workflows/terraform.yaml@1.4
        with:
            terraform_version: '1.7.5'
            working-directory: ./
        secrets:
            tf_api_token: ${{ secrets.TF_API_TOKEN }}
